version: "3.8"
services:
  react-prod:
    container_name: fe-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=production