export const dummyData = [
    {
        id: "m5gr84i8",
        nra: "290/UKM_IK/XXVI/2021",
        name: "Suherman Sumitro",
        jenisKelamin: "Laki-laki",
        prodi: "D3 - Sistem Informasi Akuntansi",
        roleSubrole: "Super Admin",
        status: "Active" || "Inactive",
        action: "abc",
    },
    {
        id: "m5gr84i9",
        nra: "291/UKM_IK/XXVI/2021",
        name: "Sumanto Wicaksono",
        jenisKelamin: "Laki-laki",
        prodi: "S1 - Informatika",
        roleSubrole: "Admin",
        status: "Active",
        action: "abc",
    },
    {
        id: "m5gr84i2",
        nra: "292/UKM_IK/XXVI/2021",
        name: "Herlambang Sunandar",
        jenisKelamin: "Laki-laki",
        prodi: "D3 - Sistem Informasi Akuntansi",
        roleSubrole: "PH - Minat & Bakat",
        status: "Active",
        action: "abc",
    },
    {
        id: "m5gr84i6",
        nra: "293/UKM_IK/XXVI/2021",
        name: "Amirudin Sohibul",
        jenisKelamin: "Laki-laki",
        prodi: "D3 - Sistem Informasi Akuntansi",
        roleSubrole: "PH - Pendidikan",
        status: "Active",
        action: "abc",
    },
    {
        id: "m5gr84i8",
        nra: "294/UKM_IK/XXVI/2021",
        name: "Januar Umarulin",
        jenisKelamin: "Perempuan",
        prodi: "S1 - Informatika",
        roleSubrole: "PH - Keanggotaan",
        status: "Active",
        action: "abc",
    },
    {
        id: "m5gr82i9",
        nra: "295/UKM_IK/XXVI/2021",
        name: "Yusseno Kusnandar",
        jenisKelamin: "Laki-laki",
        prodi: "D3 - Sistem Informasi Akuntansi",
        roleSubrole: "PH - Publikasi",
        status: "Inactive",
        action: "abc",
    },
    // Add more dummy data as needed
];